version: "3"

services:
    db:
      image: postgres
      env_file:
        - ".env"
      expose:
        - "5432"
      restart: always

    daphne:
        build: ./daphne
        container_name: daphne
        env_file:
            - ".env"
        volumes:
            - ./daphne:${APP_ROOT}
            - static:${STATIC_ROOT}
            - media:${MEDIA_ROOT}
        expose:
            - "8000"
        depends_on:
          - db
        restart: always

    nginx:
        image: nginx:alpine-slim
        env_file:
            - ".env"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
            - static:${STATIC_ROOT}
            - media:${MEDIA_ROOT}
        links:
            - daphne
        ports:
            - 80:80
        restart: always
        command: /bin/bash -c "certbot renew --quiet --no-self-upgrade --email ${EMAIL_ADDRESS} -d ${SERVER_NAME}"

    redis:
      image: redis:7
      env_file:
        - ".env"
      restart: always

volumes:
    static:
        driver: local
    media:
        driver: local
    redis:
        driver: local
    db:
      driver: local
