version: "3"

services:
    db:
      image: postgres
      env_file:
        - ".env"
      expose:
        - "5432"
      restart: always

    daphne:
        build: ./daphne
        container_name: daphne
        env_file:
            - ".env"
        volumes:
            - ./daphne:${APP_ROOT}
            - static:${STATIC_ROOT}
            - media:${MEDIA_ROOT}
        expose:
            - "8000"
        depends_on:
          - db
        restart: always

    nginx:
        image: nginx
        env_file:
            - ".env"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
            - /etc/letsencrypt:/etc/letsencrypt
            - static:${STATIC_ROOT}
            - media:${MEDIA_ROOT}
        links:
            - daphne
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
          - certbot

    redis:
      image: redis:7
      env_file:
        - ".env"
      restart: always

    certbot:
      image: certbot/certbot:v1.7.0
      env_file:
        - ".env"
      volumes:
        - /etc/letsencrypt:/etc/letsencrypt
      command: certbot certonly --standalone -d ${SERVER_NAME} --email ${EMAIL_ADDRESS} --agree-tos --no-eff-email

volumes:
    static:
        driver: local
    media:
        driver: local
    redis:
        driver: local
    db:
      driver: local
