# Generated by Django 4.1.1 on 2022-10-26 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=150, verbose_name='問題')),
                ('choiceA', models.CharField(max_length=50, verbose_name='選択肢A')),
                ('choiceB', models.CharField(max_length=50, verbose_name='選択肢B')),
                ('choiceC', models.CharField(max_length=50, verbose_name='選択肢C')),
                ('choiceD', models.CharField(max_length=50, verbose_name='選択肢D')),
                ('correctChoice', models.CharField(choices=[(None, '正解を選択'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='正解')),
            ],
        ),
        migrations.CreateModel(
            name='QuizEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField(auto_now_add=True, verbose_name='解答開始時刻')),
                ('endTime', models.DateTimeField(null=True, verbose_name='解答終了時刻')),
                ('status', models.CharField(choices=[('READY', '出題前'), ('OPENED', '出題中'), ('CLOSED', '選択締め切り'), ('COLLECTING', '解答受付中'), ('SCORED', '採点済み')], default='READY', max_length=20, verbose_name='状態')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='quiz.quizevents')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.questions')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='名無しさん', max_length=50, verbose_name='ニックネーム')),
            ],
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('correctNums', models.IntegerField(default=0, verbose_name='正解数')),
                ('temp_rank', models.IntegerField(default=-1, verbose_name='あなたの順位')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joined_users', to='quiz.quizevents')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='quiz.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='quiz.quizzes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.userdata')),
            ],
        ),
        migrations.AddField(
            model_name='quizevents',
            name='currently_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='quiz.quizzes'),
        ),
        migrations.AddConstraint(
            model_name='userscores',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_score'),
        ),
        migrations.AddConstraint(
            model_name='useranswers',
            constraint=models.UniqueConstraint(fields=('quiz', 'user'), name='unique_answer'),
        ),
    ]
