# Generated by Django 4.1.1 on 2022-10-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizevents',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
