# Generated by Django 4.1.1 on 2022-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_questions_correctchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='nickname',
            field=models.CharField(default='名無しさん', max_length=50, verbose_name='ニックネーム'),
        ),
    ]
