# Generated by Django 4.1.1 on 2022-10-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quizevents_currently_quiz_quizzes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='status',
        ),
    ]
