# Generated by Django 4.1.1 on 2022-10-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_quizzes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='status',
            field=models.CharField(choices=[('READY', '出題前'), ('OPENED', '出題中'), ('CLOSED', '選択締め切り'), ('COLLECTING', '解答受付中'), ('SCORED', '採点済み')], default='READY', max_length=20, verbose_name='状態'),
        ),
    ]
