# Generated by Django 4.1.1 on 2022-09-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizevents_quizzes_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='得点')),
                ('correctNums', models.IntegerField(default=0, verbose_name='正解数')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='correctNums',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='score',
        ),
        migrations.AddConstraint(
            model_name='useranswers',
            constraint=models.UniqueConstraint(fields=('quiz', 'user'), name='unique_answer'),
        ),
        migrations.AddField(
            model_name='userscores',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.quizevents'),
        ),
        migrations.AddField(
            model_name='userscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.userdata'),
        ),
        migrations.AddConstraint(
            model_name='userscores',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='unique_score'),
        ),
    ]
