# Generated by Django 4.1.1 on 2022-09-18 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_userscores_remove_userdata_correctnums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='joined_users', to='quiz.quizevents'),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='quiz.userdata'),
        ),
    ]
